#BeginMacro(Threshhold<-1,0,0>)
if ( (-1, 0,0) >= 21, 1, 0)
#EndMacro

#BeginMacro(Threshhold<1,0,0>)
if ( (1,0,0) >= 21, 1, 0)
#EndMacro

#BeginMacro(Threshhold<0,1,0>)
if ( (0,1,0) >=21, 1, 0)
#EndMacro

#BeginMacro(Threshhold<0,-1,0>)
if ( (0,-1,0) >=21, 1, 0)
#EndMacro

#BeginMacro(Threshhold<-1,1,0>)
if ( (-1,1,0) >=21, 1, 0)
#EndMacro

#BeginMacro(Threshhold<1,1,0>)
if ( (1,1,0) >=21, 1, 0)
#EndMacro

#BeginMacro(Threshhold<-1,-1,0>)
if ( (-1,-1,0) >=21, 1, 0)
#EndMacro

#BeginMacro(Threshhold<1,-1,0>)
if ( (1,-1,0) >=21, 1, 0)
#EndMacro


#BeginMacro(Value<-1,0,0>)
if ( (-1, 0,0) >=21, (-1, 0,0)*0.3, 0)
#EndMacro

#BeginMacro(Value<1,0,0>)
if ( (1,0,0) >=21, (1,0,0)*0.3, 0)
#EndMacro

#BeginMacro(Value<0,1,0>)
if ( (0,1,0) >=21, (0,1,0)*0.3, 0)
#EndMacro

#BeginMacro(Value<0,-1,0>)
if ( (0,-1,0) >=21, (0,-1,0)*0.3, 0)
#EndMacro

#BeginMacro(Value<-1,1,0>)
if ( (-1,1,0) >=21, (-1,1,0)*0.3, 0)
#EndMacro

#BeginMacro(Value<1,1,0>)
if ( (1,1,0) >=21, (1,1,0)*0.3, 0)
#EndMacro

#BeginMacro(Value<-1,-1,0>)
if ( (-1,-1,0) >=21, (-1,-1,0)*0.3, 0)
#EndMacro

#BeginMacro(Value<1,-1,0>)
if ( (1,-1,0) >=21, 0.3*(1,-1,0), 0)
#EndMacro





